<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Siddivinayak" failures="3" tests="20" name="automatedtest.CapstoneProject" time="49.284" errors="0" timestamp="2025-01-25T14:15:15 IST" skipped="0">
  <testcase classname="automatedtest.CapstoneProject" name="verifyNavigationMenu" time="9.131"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyNavigationElement_1" time="0.046"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyNavigationElement_2" time="0.036"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyNavigationElement_3" time="0.034"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyNavigationElement_4" time="0.034"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyNavigationElement_5" time="0.035"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyNavigationElement_6" time="0.032"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyNavigationElement_7" time="0.036"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="searchBarFunctionality" time="2.175"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyHealthProgram_1" time="0.423">
    <failure message="Content mismatch expected [TOBACCO] but found [Search results for: Health programs]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Content mismatch expected [TOBACCO] but found [Search results for: Health programs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at automatedtest.CapstoneProject.verifyHealthProgram_1(CapstoneProject.java:209)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyHealthProgram_1 -->
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyHealthProgram_2" time="0.358">
    <failure message="Content mismatch expected [AHEC SCHOLARS] but found [Search results for: Health programs]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Content mismatch expected [AHEC SCHOLARS] but found [Search results for: Health programs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at automatedtest.CapstoneProject.verifyHealthProgram_2(CapstoneProject.java:233)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyHealthProgram_2 -->
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyHealthProgram_3" time="0.395">
    <failure message="Content mismatch expected [HEALTHY AGING] but found [Search results for: Health programs]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Content mismatch expected [HEALTHY AGING] but found [Search results for: Health programs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at automatedtest.CapstoneProject.verifyHealthProgram_3(CapstoneProject.java:257)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyHealthProgram_3 -->
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyHealthProgram_4" time="0.496"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="contactUsPageAddress" time="1.726"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="contactUsPageCallUs" time="0.941"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="contactUsPageFax" time="0.952"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="contactUsPageEmailUs" time="0.935"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="verifyForm" time="6.520"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="userLogin" time="17.440"/>
  <system-out/>
  <testcase classname="automatedtest.CapstoneProject" name="passwordRecovery" time="7.539"/>
  <system-out/>
</testsuite> <!-- automatedtest.CapstoneProject -->
